steps:
  - id: 'BUILD DOCKER IMAGE'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-builder:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-builder:latest'
      - '.'
    env:
      - 'NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY'
      - 'NEXT_PUBLIC_SITE_URL=$_NEXT_PUBLIC_SITE_URL'
      - 'NEXT_PUBLIC_APP_URL=$_NEXT_PUBLIC_APP_URL'

  - id: 'PUSH DOCKER IMAGE'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/resume-builder:$COMMIT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/resume-builder:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/resume-builder:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'